### ISSUE TITLE
Running out of system memory when using this. 

### ISSUE THREAD

**Issue by CosmicEvil** [charlesveasey/ofxDomemaster#2]
If i use the domemaster addon, and let it run for about 30 seconds, my whole system crashes. Do you have any idea what might cause this? 

Edit: Found what was causing this, was a mistake on my part, my excuses for posting this issue.

**Comment by charlesveasey** [comment]
i haven't seen this. which OS and oF version? thanks for reporting.

**Comment by charlesveasey** [comment]
thanks for the follow up
