### ISSUE TITLE
rotating the camera

### ISSUE THREAD

**Issue by Blindsp0t-creative** [charlesveasey/ofxDomemaster#3]
Hi,
First of all, thank you for this wonderful addon.

I'm wondering if you have a solution for rotating the camera point of view inside the 3d scene? 
I'm currently playing with 'setOrientation()' in the resize() method but it's a nightmare compositing the angles when rotating around more than one axis.

Any advice maybe ... ?
Antoine

**Comment by charlesveasey** [comment]
Hello,
Try using ofNode. You should be able to set the dome camera rig as a child and transform the node.

**Comment by Blindsp0t-creative** [comment]
thank you a lot. that's indeed the way to go :)
